### ISSUE TITLE
Program not detecting the Epilogue

### ISSUE THREAD

**Issue by Heroice18** [GavriloviciEduard/ShinyHunter#1]
Hi, so I tried installing the program to test it out so when I get to an instance where I can soft reset I'd be able to use it. However when I run it I get the following error

![image](https://user-images.githubusercontent.com/17243828/216772190-4a2d82ac-19d1-472e-ab9a-8ea0dfa52db5.png)

**Comment by alejiososa** [comment]
run the hunter first, then plug in your GB operator, it should hook. i got it to work this way

**Comment by Heroice18** [comment]
When I try without plugging it in I then get the option to pick target colors and reference. I couldn't find instructions on your ReadMe about that and with my testing I keep getting to a few errors.

![image](https://user-images.githubusercontent.com/17243828/224557857-e7f825d5-d570-48ba-9355-f7698d571077.png)

**Comment by alejiososa** [comment]
Watch the video in the Github page, it’ll show you what to pick

**Comment by Heroice18** [comment]
Okay that seems to work now. I have to start the epilogue software without plugging in the hardware, run the program, and then select the options. Thank you! Can't wait to see the other modes get implemented!
